version: '2'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    restart: 'on-failure'
    environment:
      - LED_MATRIX_ROWS=32
      - LED_MATRIX_COLUMNS=64
      - LED_MATRIX_COUNT=2
    networks:
      - local
    privileged: true
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    restart: 'on-failure'
    networks:
      - local
networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.254
