version: '3.6'
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    restart: 'on-failure'
    command:
      - --port=8080
      - --led_matrix_rows=${LED_MATRIX_ROWS}
      - --led_matrix_columns=${LED_MATRIX_COLUMNS}
      - --led_matrix_count=${LED_MATRIX_COUNT}
    privileged: true
  website:
    container_name: website
    build:
      context: ./website
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    restart: 'on-failure'
